import type { SettingItem } from '../SettingItem/SettingItem.ts'
import * as InputName from '../InputName/InputName.ts'
import * as SettingItemType from '../SettingItemType/SettingItemType.ts'
import * as SettingStrings from '../SettingStrings/SettingStrings.ts'

export const getSettingItemsEditor = (): readonly SettingItem[] => {
  return [
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.fontSizeDescription(),
      heading: SettingStrings.fontSize(),
      id: 'editor.fontSize',
      type: SettingItemType.Number,
      validate(value): string {
        if (typeof value !== 'number') {
          return 'font size must be of type number'
        }
        const minFontSize = 10
        const maxFontSize = 100
        if (value < minFontSize) {
          return 'font size must be at least 10'
        }
        if (value > maxFontSize) {
          return 'font size must not be greater than 100'
        }
        return ''
      },
      value: 15,
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.fontFamilyDescription(),
      heading: SettingStrings.fontFamily(),
      id: 'editor.fontFamily',
      type: SettingItemType.String,
      value: 'Fira Code',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.wordWrapDescription(),
      heading: SettingStrings.wordWrap(),
      id: 'editor.wordWrap',
      options: [
        {
          id: 'editor.on',
          label: 'On', // i18n
        },
        {
          id: 'editor.off',
          label: 'off', // i18n
        },
      ],
      type: SettingItemType.Enum,
      value: 'off',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.lineNumbersDescription(),
      heading: SettingStrings.lineNumbers(),
      id: 'editor.lineNumbers',
      options: [
        {
          id: 'editor.on',
          label: 'On', // i18n
        },
        {
          id: 'editor.off',
          label: 'off', // i18n
        },
      ],
      type: SettingItemType.Enum,
      value: 'on',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.minimapDescription(),
      heading: SettingStrings.minimap(),
      id: 'editor.minimap',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.scrollBeyondLastLineDescription(),
      heading: SettingStrings.scrollBeyondLastLine(),
      id: 'editor.scrollBeyondLastLine',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.smoothScrollingDescription(),
      heading: SettingStrings.smoothScrolling(),
      id: 'editor.smoothScrolling',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.cursorBlinkingDescription(),
      heading: SettingStrings.cursorBlinking(),
      id: 'editor.cursorBlinking',
      type: SettingItemType.String,
      value: 'blink',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.cursorStyleDescription(),
      heading: SettingStrings.cursorStyle(),
      id: 'editor.cursorStyle',
      type: SettingItemType.String,
      value: 'line',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.cursorWidthDescription(),
      heading: SettingStrings.cursorWidth(),
      id: 'editor.cursorWidth',
      type: SettingItemType.Number,
      value: '0',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.tabSizeDescription(),
      heading: SettingStrings.tabSize(),
      id: 'editor.tabSize',
      type: SettingItemType.Number,
      validate(value): string {
        if (typeof value !== 'number') {
          return 'font size must be of type number'
        }
        const minTabSize = 1
        const maxTabSize = 8
        if (value < minTabSize) {
          return `tab size must be at least ${minTabSize}`
        }
        if (value > maxTabSize) {
          return `tab size must not be greater than ${maxTabSize}`
        }
        return ''
      },
      value: '4',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.insertSpacesDescription(),
      heading: SettingStrings.insertSpaces(),
      id: 'editor.insertSpaces',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.detectIndentationDescription(),
      heading: SettingStrings.detectIndentation(),
      id: 'editor.detectIndentation',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.trimAutoWhitespaceDescription(),
      heading: SettingStrings.trimAutoWhitespace(),
      id: 'editor.trimAutoWhitespace',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.largeFileOptimizationsDescription(),
      heading: SettingStrings.largeFileOptimizations(),
      id: 'editor.largeFileOptimizations',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.renderWhitespaceDescription(),
      heading: SettingStrings.renderWhitespace(),
      id: 'editor.renderWhitespace',
      type: SettingItemType.String,
      value: 'selection',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.renderControlCharactersDescription(),
      heading: SettingStrings.renderControlCharacters(),
      id: 'editor.renderControlCharacters',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.renderLineHighlightDescription(),
      heading: SettingStrings.renderLineHighlight(),
      id: 'editor.renderLineHighlight',
      type: SettingItemType.String,
      value: 'line',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.codeLensDescription(),
      heading: SettingStrings.codeLens(),
      id: 'editor.codeLens',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.foldingDescription(),
      heading: SettingStrings.folding(),
      id: 'editor.folding',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.showFoldingControlsDescription(),
      heading: SettingStrings.showFoldingControls(),
      id: 'editor.showFoldingControls',
      type: SettingItemType.String,
      value: 'mouseover',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.unfoldOnClickAfterEndDescription(),
      heading: SettingStrings.unfoldOnClickAfterEnd(),
      id: 'editor.unfoldOnClickAfterEnd',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.linksDescription(),
      heading: SettingStrings.links(),
      id: 'editor.links',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.colorDecoratorsDescription(),
      heading: SettingStrings.colorDecorators(),
      id: 'editor.colorDecorators',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.lightbulbDescription(),
      heading: SettingStrings.lightbulb(),
      id: 'editor.lightbulb',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.codeActionsOnSaveDescription(),
      heading: SettingStrings.codeActionsOnSave(),
      id: 'editor.codeActionsOnSave',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.formatOnPasteDescription(),
      heading: SettingStrings.formatOnPaste(),
      id: 'editor.formatOnPaste',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.formatOnTypeDescription(),
      heading: SettingStrings.formatOnType(),
      id: 'editor.formatOnType',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.acceptSuggestionOnCommitCharacterDescription(),
      heading: SettingStrings.acceptSuggestionOnCommitCharacter(),
      id: 'editor.acceptSuggestionOnCommitCharacter',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.acceptSuggestionOnEnterDescription(),
      heading: SettingStrings.acceptSuggestionOnEnter(),
      id: 'editor.acceptSuggestionOnEnter',
      type: SettingItemType.String,
      value: 'on',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.tabCompletionDescription(),
      heading: SettingStrings.tabCompletion(),
      id: 'editor.tabCompletion',
      type: SettingItemType.String,
      value: 'on',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.wordBasedSuggestionsDescription(),
      heading: SettingStrings.wordBasedSuggestions(),
      id: 'editor.wordBasedSuggestions',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.suggestOnTriggerCharactersDescription(),
      heading: SettingStrings.suggestOnTriggerCharacters(),
      id: 'editor.suggestOnTriggerCharacters',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.quickSuggestionsDescription(),
      heading: SettingStrings.quickSuggestions(),
      id: 'editor.quickSuggestions',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.parameterHintsDescription(),
      heading: SettingStrings.parameterHints(),
      id: 'editor.parameterHints',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.autoClosingBracketsDescription(),
      heading: SettingStrings.autoClosingBrackets(),
      id: 'editor.autoClosingBrackets',
      type: SettingItemType.String,
      value: 'always',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.autoClosingQuotesDescription(),
      heading: SettingStrings.autoClosingQuotes(),
      id: 'editor.autoClosingQuotes',
      type: SettingItemType.String,
      value: 'always',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.autoClosingOvertypeDescription(),
      heading: SettingStrings.autoClosingOvertype(),
      id: 'editor.autoClosingOvertype',
      type: SettingItemType.String,
      value: 'auto',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.autoClosingDeleteDescription(),
      heading: SettingStrings.autoClosingDelete(),
      id: 'editor.autoClosingDelete',
      type: SettingItemType.String,
      value: 'auto',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.autoSurroundDescription(),
      heading: SettingStrings.autoSurround(),
      id: 'editor.autoSurround',
      type: SettingItemType.String,
      value: 'quotes',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.bracketPairColorizationDescription(),
      heading: SettingStrings.bracketPairColorization(),
      id: 'editor.bracketPairColorization',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.guidesDescription(),
      heading: SettingStrings.guides(),
      id: 'editor.guides',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.dragAndDropDescription(),
      heading: SettingStrings.dragAndDrop(),
      id: 'editor.dragAndDrop',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.copyWithSyntaxHighlightingDescription(),
      heading: SettingStrings.copyWithSyntaxHighlighting(),
      id: 'editor.copyWithSyntaxHighlighting',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.multiCursorModifierDescription(),
      heading: SettingStrings.multiCursorModifier(),
      id: 'editor.multiCursorModifier',
      type: SettingItemType.String,
      value: 'alt',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.multiCursorPasteDescription(),
      heading: SettingStrings.multiCursorPaste(),
      id: 'editor.multiCursorPaste',
      type: SettingItemType.String,
      value: 'full',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.occurrencesHighlightDescription(),
      heading: SettingStrings.occurrencesHighlight(),
      id: 'editor.occurrencesHighlight',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.selectionHighlightDescription(),
      heading: SettingStrings.selectionHighlight(),
      id: 'editor.selectionHighlight',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.semanticHighlightingDescription(),
      heading: SettingStrings.semanticHighlighting(),
      id: 'editor.semanticHighlighting',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.tokenColorCustomizationsDescription(),
      heading: SettingStrings.tokenColorCustomizations(),
      id: 'editor.tokenColorCustomizations',
      type: SettingItemType.String,
      value: '{}',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.workbenchColorCustomizationsDescription(),
      heading: SettingStrings.workbenchColorCustomizations(),
      id: 'editor.workbenchColorCustomizations',
      type: SettingItemType.String,
      value: '{}',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.editorColorCustomizationsDescription(),
      heading: SettingStrings.editorColorCustomizations(),
      id: 'editorColorCustomizations',
      type: SettingItemType.String,
      value: '{}',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffEditorDescription(),
      heading: SettingStrings.diffEditor(),
      id: 'editor.diffEditor',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffWordWrapDescription(),
      heading: SettingStrings.diffWordWrap(),
      id: 'editor.diffWordWrap',
      type: SettingItemType.String,
      value: 'inherit',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffCodeLensDescription(),
      heading: SettingStrings.diffCodeLens(),
      id: 'editor.diffCodeLens',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffRenderSideBySideDescription(),
      heading: SettingStrings.diffRenderSideBySide(),
      id: 'editor.diffRenderSideBySide',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffIgnoreTrimWhitespaceDescription(),
      heading: SettingStrings.diffIgnoreTrimWhitespace(),
      id: 'editor.diffIgnoreTrimWhitespace',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffRenderIndicatorsDescription(),
      heading: SettingStrings.diffRenderIndicators(),
      id: 'editor.diffRenderIndicators',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffRenderOverviewRulerDescription(),
      heading: SettingStrings.diffRenderOverviewRuler(),
      id: 'editor.diffRenderOverviewRuler',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.diffRenderMarginRevertIconDescription(),
      heading: SettingStrings.diffRenderMarginRevertIcon(),
      id: 'editor.diffRenderMarginRevertIcon',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.insertModeDescription(),
      heading: SettingStrings.insertMode(),
      id: 'editor.insertMode',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.overwriteModeDescription(),
      heading: SettingStrings.overwriteMode(),
      id: 'editor.overwriteMode',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.readOnlyDescription(),
      heading: SettingStrings.readOnly(),
      id: 'editor.readOnly',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.accessibilitySupportDescription(),
      heading: SettingStrings.accessibilitySupport(),
      id: 'editor.accessibilitySupport',
      type: SettingItemType.String,
      value: 'auto',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.autoIndentDescription(),
      heading: SettingStrings.autoIndent(),
      id: 'editor.autoIndent',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.bracketMatchingDescription(),
      heading: SettingStrings.bracketMatching(),
      id: 'editor.bracketMatching',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.centeredLayoutDescription(),
      heading: SettingStrings.centeredLayout(),
      id: 'editor.centeredLayout',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.columnSelectionDescription(),
      heading: SettingStrings.columnSelection(),
      id: 'editor.columnSelection',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.contextmenuDescription(),
      heading: SettingStrings.contextmenu(),
      id: 'editor.contextmenu',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.cursorSmoothCaretAnimationDescription(),
      heading: SettingStrings.cursorSmoothCaretAnimation(),
      id: 'editor.cursorSmoothCaretAnimation',
      type: SettingItemType.String,
      value: 'off',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.cursorSurroundingLinesDescription(),
      heading: SettingStrings.cursorSurroundingLines(),
      id: 'editor.cursorSurroundingLines',
      type: SettingItemType.Number,
      value: '3',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.cursorSurroundingLinesStyleDescription(),
      heading: SettingStrings.cursorSurroundingLinesStyle(),
      id: 'editor.cursorSurroundingLinesStyle',
      type: SettingItemType.String,
      value: 'all',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.disableMonospaceOptimizationsDescription(),
      heading: SettingStrings.disableMonospaceOptimizations(),
      id: 'editor.disableMonospaceOptimizations',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.emptySelectionClipboardDescription(),
      heading: SettingStrings.emptySelectionClipboard(),
      id: 'editor.emptySelectionClipboard',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.extraEditorClassNameDescription(),
      heading: SettingStrings.extraEditorClassName(),
      id: 'editor.extraEditorClassName',
      type: SettingItemType.String,
      value: '',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.fastScrollSensitivityDescription(),
      heading: SettingStrings.fastScrollSensitivity(),
      id: 'editor.fastScrollSensitivity',
      type: SettingItemType.Number,
      value: '5',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.findDescription(),
      heading: SettingStrings.find(),
      id: 'editor.find',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.fixedOverflowWidgetsDescription(),
      heading: SettingStrings.fixedOverflowWidgets(),
      id: 'editor.fixedOverflowWidgets',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.foldingStrategyDescription(),
      heading: SettingStrings.foldingStrategy(),
      id: 'editor.foldingStrategy',
      type: SettingItemType.String,
      value: 'auto',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.fontLigaturesDescription(),
      heading: SettingStrings.fontLigatures(),
      id: 'editor.fontLigatures',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.glyphMarginDescription(),
      heading: SettingStrings.glyphMargin(),
      id: 'editor.glyphMargin',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.gotoLocationDescription(),
      heading: SettingStrings.gotoLocation(),
      id: 'editor.gotoLocation',
      type: SettingItemType.String,
      value: 'mouse',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.hideCursorInOverviewRulerDescription(),
      heading: SettingStrings.hideCursorInOverviewRuler(),
      id: 'editor.hideCursorInOverviewRuler',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.hoverDescription(),
      heading: SettingStrings.hover(),
      id: 'editor.hover',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.inDiffEditorDescription(),
      heading: SettingStrings.inDiffEditor(),
      id: 'editor.inDiffEditor',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.letterSpacingDescription(),
      heading: SettingStrings.letterSpacing(),
      id: 'editor.letterSpacing',
      type: SettingItemType.Number,
      value: '0',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.lightbulbEnabledDescription(),
      heading: SettingStrings.lightbulbEnabled(),
      id: 'editor.lightbulbEnabled',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.lineDecorationsWidthDescription(),
      heading: SettingStrings.lineDecorationsWidth(),
      id: 'editor.lineDecorationsWidth',
      type: SettingItemType.Number,
      value: '10',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.lineHeightDescription(),
      heading: SettingStrings.lineHeight(),
      id: 'editor.lineHeight',
      type: SettingItemType.Number,
      value: '0',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.matchBracketsDescription(),
      heading: SettingStrings.matchBrackets(),
      id: 'editor.matchBrackets',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.minimapEnabledDescription(),
      heading: SettingStrings.minimapEnabled(),
      id: 'editor.minimapEnabled',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.mouseWheelScrollSensitivityDescription(),
      heading: SettingStrings.mouseWheelScrollSensitivity(),
      id: 'editor.mouseWheelScrollSensitivity',
      type: SettingItemType.Number,
      value: '1',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.mouseWheelZoomDescription(),
      heading: SettingStrings.mouseWheelZoom(),
      id: 'editor.mouseWheelZoom',
      type: SettingItemType.Boolean,
      value: 'false',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.multiCursorMergeOverlappingDescription(),
      heading: SettingStrings.multiCursorMergeOverlapping(),
      id: 'editor.multiCursorMergeOverlapping',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.overviewRulerBorderDescription(),
      heading: SettingStrings.overviewRulerBorder(),
      id: 'editor.overviewRulerBorder',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.overviewRulerLanesDescription(),
      heading: SettingStrings.overviewRulerLanes(),
      id: 'editor.overviewRulerLanes',
      type: SettingItemType.Number,
      value: '3',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.peekWidgetDefaultFocusDescription(),
      heading: SettingStrings.peekWidgetDefaultFocus(),
      id: 'editor.peekWidgetDefaultFocus',
      type: SettingItemType.String,
      value: 'editor',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.quickSuggestionsDelayDescription(),
      heading: SettingStrings.quickSuggestionsDelay(),
      id: 'editor.quickSuggestionsDelay',
      type: SettingItemType.Number,
      value: '10',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.renderFinalNewlineDescription(),
      heading: SettingStrings.renderFinalNewline(),
      id: 'editor.renderFinalNewline',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.renderValidationDecorationsDescription(),
      heading: SettingStrings.renderValidationDecorations(),
      id: 'editor.renderValidationDecorations',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.revealHorizontalRightPaddingDescription(),
      heading: SettingStrings.revealHorizontalRightPadding(),
      id: 'editor.revealHorizontalRightPadding',
      type: SettingItemType.Number,
      value: '30',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.roundedSelectionDescription(),
      heading: SettingStrings.roundedSelection(),
      id: 'editor.roundedSelection',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.rulersDescription(),
      heading: SettingStrings.rulers(),
      id: 'editor.rulers',
      type: SettingItemType.String,
      value: '[]',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.scrollBeyondLastColumnDescription(),
      heading: SettingStrings.scrollBeyondLastColumn(),
      id: 'editor.scrollBeyondLastColumn',
      type: SettingItemType.Number,
      value: '5',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.scrollbarDescription(),
      heading: SettingStrings.scrollbar(),
      id: 'editor.scrollbar',
      type: SettingItemType.String,
      value: 'auto',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.scrollPredominantAxisDescription(),
      heading: SettingStrings.scrollPredominantAxis(),
      id: 'editor.scrollPredominantAxis',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.selectionClipboardDescription(),
      heading: SettingStrings.selectionClipboard(),
      id: 'editor.selectionClipboard',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: 'Editor background color',
      heading: 'Editor background',
      id: 'editor.background',
      type: SettingItemType.Color,
      value: '#567567',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.showUnusedDescription(),
      heading: SettingStrings.showUnused(),
      id: 'editor.showUnused',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.snippetSuggestionsDescription(),
      heading: SettingStrings.snippetSuggestions(),
      id: 'editor.snippetSuggestions',
      type: SettingItemType.String,
      value: 'bottom',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.suggestDescription(),
      heading: SettingStrings.suggest(),
      id: 'editor.suggest',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.suggestFontSizeDescription(),
      heading: SettingStrings.suggestFontSize(),
      id: 'editor.suggestFontSize',
      type: SettingItemType.Number,
      value: '0',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.suggestLineHeightDescription(),
      heading: SettingStrings.suggestLineHeight(),
      id: 'editor.suggestLineHeight',
      type: SettingItemType.Number,
      value: '0',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.suggestSelectionDescription(),
      heading: SettingStrings.suggestSelection(),
      id: 'editor.suggestSelection',
      type: SettingItemType.String,
      value: 'recentlyUsed',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.useTabStopsDescription(),
      heading: SettingStrings.useTabStops(),
      id: 'editor.useTabStops',
      type: SettingItemType.Boolean,
      value: 'true',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.wordSeparatorsDescription(),
      heading: SettingStrings.wordSeparators(),
      id: 'editor.wordSeparators',
      type: SettingItemType.String,
      value: '`~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?',
    },
    {
      category: InputName.TextEditorTab,
      description: SettingStrings.wrappingIndentDescription(),
      heading: SettingStrings.wrappingIndent(),
      id: 'editor.wrappingIndent',
      type: SettingItemType.String,
      value: 'same',
    },
  ]
}
