import type { SettingsState } from '../SettingsState/SettingsState.ts'

export const createDefaultState = (): SettingsState => {
  return {
    breakPointsExpanded: false,
    breakPointsVisible: true,
    deltaY: 0,
    filteredItems: [],
    filteredItemsCount: 0,
    focus: 0,
    focusSource: 0,
    height: 600,
    highlightsEnabled: false,
    history: [],
    historyIndex: -1,
    id: 1,
    inputSource: 0,
    itemHeight: 100,
    items: [],
    maxLineY: 0,
    minContentWidth: 300,
    minLineY: 0,
    modifiedSettings: {},
    preferences: {},
    scrollBarMinHeight: 20,
    scrollBarThumbHeight: 0,
    scrollBarThumbTop: 0,
    scrollOffset: 0,
    searchValue: '',
    sideBarMinWidth: 100,
    sideBarWidth: 200,
    tabs: [],
    uri: 'test://uri',
    visibleItems: [],
    width: 800,
    x: 0,
    y: 0,
  }
}
